Update test-scripts.yml

diff --git a/.github/workflows/test-scripts.yml b/.github/workflows/test-scripts.yml
--- a/.github/workflows/test-scripts.yml
+++ b/.github/workflows/test-scripts.yml
@@ -1,51 +1,32 @@
-name: Test Scripts
+name: Python Test
 
-on:
-  push:
-    branches:
-      - main
+on: [push, pull_request]
 
 jobs:
-  test-scripts:
+  test:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Clean up GitHub Actions cache
-    run: |
-      rm -rf $RUNNER_TOOL_CACHE/Python
-
-    - name: Checkout Repository
+    - name: Checkout repository
       uses: actions/checkout@v2
 
     - name: Set up Python
-      uses: actions/setup-python@v2
+      uses: actions/setup-python@v3
       with:
-        python-version: 3.10
+        python-version: 3.8
 
-    - name: Install Dependencies
+    - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
-
-    - name: Test Scripts
+    - name: Run tests
       run: |
-        # Ejecutar todos los scripts de Python en el directorio actual
-        find . -name "*.py" -exec python {} \;
-
-  check-syntax:
-    runs-on: ubuntu-latest
-
-    steps:
-    - name: Checkout Repository
-      uses: actions/checkout@v2
-
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: 3.10
-
-    - name: Install Flake8
-      run: pip install flake8
-
-    - name: Check Python Syntax
-      run: flake8 .
+        # Assuming your tests are in the 'tests' directory
+        ls
+        pytest tests/
+    - name: Check for failed tests
+      run: |
+        if [ $? -ne 0 ]; then
+          echo "Tests failed!"
+          exit 1
+        fi
